### ISSUE TITLE
Fix error with: $

### ISSUE THREAD

**Issue by datvq** [zjffun/vscode-snippets-manager#17]
Thank you very much for your excellent extension, it's remarkably useful. However, I encountered a problem when trying to create snippets for code snippets that contain the dollar sign ($), such as `${file}` or `$$(file)`. The dollar sign disappears or doesn't appear correctly in the generated code. I would greatly appreciate it if you could fix this. Thanks.

**Comment by zjffun** [comment]
To fix this, you can add `\` before `$`, for example `\${file}`. Because `$` has special purpose, like tabstops, placeholders or choice.
See [Grammar - Snippets in Visual Studio Code](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar) and [Syntax - Snippets in Visual Studio Code](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax).
Thank you.

**Comment by datvq** [comment]
I understand that, but if we do that, the code template in the clipboard and the code input won't match. If there are multiple positions, manual editing won't be appropriate. Instead, I think it would be better if the parser from the snippets manager and the VS Code snippets file handle it implicitly. I apologize for the delayed response.

**Comment by zjffun** [comment]
> I understand that, but if we do that, the code template in the clipboard and the code input won't match. If there are multiple positions, manual editing won't be appropriate. Instead, I think it would be better if the parser from the snippets manager and the VS Code snippets file handle it implicitly. I apologize for the delayed response.

Yes, this is more convenient. We added escape snippet body by default when create snippets from selection, and it's available in [v0.2.0](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.2.0) 🎉.

**Comment by datvq** [comment]
Thank you, welcome v0.2.0 🎉
