### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by josersleal** [zjffun/vscode-snippets-manager#25]
thats it...
press search button, list shows, input anything, nothing changes

**Comment by zjffun** [comment]
Are there any items in the list? If there have no one, you can try to search from all snippets like:

<img width="666" alt="Screen Shot 2024-07-08 at 00 50 45" src="https://github.com/zjffun/vscode-snippets-manager/assets/25266120/8aef83d1-0999-4ad7-999e-6ad1c2bf0a27">

I also added a new feature in v0.3.8 that if no snippets found, a message will show to let user search from all snippets.

<img width="1037" alt="Screen Shot 2024-07-08 at 00 55 37" src="https://github.com/zjffun/vscode-snippets-manager/assets/25266120/10b731c6-0e1a-4d87-8e8b-de88167ac1c4">

**Comment by josersleal** [comment]
I get this on activating search:

![image](https://github.com/zjffun/vscode-snippets-manager/assets/3142072/758d73b6-e65c-46e7-90bf-12b4d0fd8ff5)

adding text does not filter the list:
![image](https://github.com/zjffun/vscode-snippets-manager/assets/3142072/71df462d-d18d-48b2-8a4f-667805d994e8)

**Comment by zjffun** [comment]
That seems a bug. Could you provide your VS Code info and the extension version? 

VS Code info like:

Version: 1.91.0 (Universal)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:54:18.541Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 21.4.0

from:

<img width="238" alt="Screen Shot 2024-07-09 at 01 06 45" src="https://github.com/zjffun/vscode-snippets-manager/assets/25266120/b754ef23-704c-4b8d-92b6-2bf360f0ecc5">

<img width="255" alt="Screen Shot 2024-07-09 at 01 06 56" src="https://github.com/zjffun/vscode-snippets-manager/assets/25266120/cf53fdf6-77bb-4a27-9d32-436bb2c6d80f">

and the extension version like v0.3.8 from:

![image](https://github.com/zjffun/vscode-snippets-manager/assets/25266120/fa0077b3-8534-4648-891a-5aa9c237959b)

I need thous info to reproduce. Because it's work well in my environment.

<img width="607" alt="Screen Shot 2024-07-09 at 01 06 19" src="https://github.com/zjffun/vscode-snippets-manager/assets/25266120/3d5b646d-42dd-4073-8a5c-bcc063dfe853">

**Comment by zjffun** [comment]
I find snippets with array type of prefix will cause this bug, and fixed it in [v0.3.11](https://github.com/zjffun/vscode-snippets-manager/releases/tag/v0.3.11). 🎉
